config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :groups do
    resources :group_members, only: [:new, :create, :destroy]

    resources :messages, only: [:create, :index]

    resources :drinks, only: [:create, :update] do
      resources :drink_responses, only: [:create]
    end
  end

  resources :friendships, only: [:index, :update]

  resources :users, only: [] do
    resources :friendships, only: [:create]
  end

  get 'profile/:id', to: 'pages#user_profile', as: :user_profile
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :user
  belongs_to :group

  has_many :drink_responses, dependent: :destroy

  validates :limit, presence: true
  validates :limit, numericality: { only_integer: true, greater_than: 0 }

  enum status: %i[boiling ready]

  after_create :broadcast_create_drink
  # after_update :broadcast_update_drink

  def broadcast_create_drink
    ActionCable.server.broadcast(
      "group_#{group.id}",
      type: 'create_drink',
      partial: render_drink(self),
      current_user_id: user.id
    )
  end

  def broadcast_update_drink
    ActionCable.server.broadcast(
      "group_#{group.id}",
      type: 'update_drink',
      partial: render_drink(self),
      current_user_id: user.id
    )
  end

  private

  def render_drink(drink)
    ApplicationController.renderer.render(
      partial: 'drinks/drink',
      locals: { drink: drink, user: user.id }
    )
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :find_group, only: :create

  def create
    @drink = Drink.new(drink_params)
    @drink.user = current_user
    @drink.group = @group
    @drink.status = 0

    @drink_responses = []
    @drink_responses << create_current_user_drink_response

    authorize @drink

    if @drink.save
      respond_to do |format|
        format.html { redirect_to group_path(@group) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'groups/show' }
        format.js
      end
    end
  end

  def update
    @drink = Drink.find(params[:id])
    authorize @drink
    @drink.status = 1

    if @drink.save
      respond_to do |format|
        format.html { redirect_to group_path(@group) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'groups/show' }
        format.js
      end
    end
  end

  private

  def create_current_user_drink_response
    DrinkResponse.create(
      user: current_user,
      drink: @drink,
      drink_type: "Tea"
    )
  end

  def drink_params
    params.require(:drink).permit(:status, :limit)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end
end

app/views/drinks/_drink.html.erb
<div id="drink-status" class="text-center" style="margin-bottom: 16px;">
  <% if user == drink.user %>
    <%= link_to "Ready to serve", group_drink_path(drink.group, drink.id), method: :put, remote: true, class: "btn btn-primary" %>
  <% elsif drink.status == 'boiling' %>
    <p>Boiling the kettle...</p>
  <% elsif drink.status == 'ready' %>
    <p>Collect your brew!</p>
  <% end %>
</div>
<div id="drink-list">
  <% if drink.drink_responses.any? %>
    <% drink.drink_responses.each do |drink_response| %>
      <%= render 'drinks/drink_card', drink_response: drink_response %>
    <% end %>
  <% end %>
</div>
<div id="drink-action" class="text-center">
  <% if user != drink.user && drink.status == 'boiling' && drink.drink_responses.map { |dr| dr.user_id }.exclude?(user.id) %>
    <%= render 'drink_responses/new_drink_responses_form', group: drink.group, drink: drink %>
  <% elsif user != drink.user && drink.status == 'ready' %>
    <%= link_to "Collect your beverage", group_path(drink.group), class: "btn btn-primary", id: "collect-drink-btn" %>
  <% end %>
</div>

app/views/drinks/_drink_card.html.erb
<div class="drink-card">
  <div class="drink-user-info">
    <%= user_avatar_photo drink_response.user, {class: "avatar"} %>
    <p><%= drink_response.user.full_name %></p>
  </div>
  <div class="drink-user-preferences">
    <p><strong>Drink:</strong> <%= drink_response.drink_type %></p>
    <p><strong>Sugar:</strong> 2</p>
    <p><strong>Milk:</strong> Dollop</p>
  </div>
</div>

app/views/drinks/create.js.erb
<% if @drink.errors.any? %>

<% else %>
  // Code to update view for drink creator
  var drinkForm = document.getElementById('new_drink');
  drinkForm.style.display = 'none';
  var drinkContainer = document.getElementById('drink-view');
  drinkContainer.insertAdjacentHTML('beforeend', '<%= j render "drink", drink: @drink, user: @drink.user, drink_responses: @drink_responses %>');
<% end %>

app/views/drinks/update.js.erb
<% if @drink.errors.any? %>

<% else %>
  var drinkStatus = document.getElementById('drink-status');
  drinkStatus.innerText = 'Collect your brew!';
<% end %>