config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :groups do
    resources :group_members, only: [:new, :create, :destroy]

    resources :messages, only: [:create, :index]

    resources :drinks, only: [:create, :update] do
      resources :drink_responses, only: [:create]
    end
  end

  resources :friendships, only: [:index, :update]

  resources :users, only: [] do
    resources :friendships, only: [:create]
  end

  get 'profile/:id', to: 'pages#user_profile', as: :user_profile
end

app/models/group.rb
class Group < ApplicationRecord
  after_initialize :default_colour

  has_many :group_members, dependent: :destroy
  has_many :members, through: :group_members
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :messages, dependent: :destroy
  has_many :drinks

  colours = [
    'rgb(255, 45, 45)',
    'rgb(97, 216, 249)',
    'rgb(72, 48, 255)',
    'rgb(0, 165, 35)',
    'rgb(216, 76, 255)',
    'rgb(255, 255, 255)'
  ]

  validates :name, length: { maximum: 26 }
  validates :colour, inclusion: { in: colours }
  validates :admin, presence: true

  def a_member?(user)
    members.each { |member| return true if member == user }
    false
  end

  def drink_in_progress?
    drinks.where(status: 0).any?
  end

  def drink_in_progress
    drinks.where(status: 0).first
  end

  def default_colour
    self.colour = 'rgb(255, 255, 255)' if colour.nil?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :colours, only: %i[new create]
  before_action :find_group, only: [:show]

  def index
    @groups = policy_scope(Group)
    @friends = policy_scope(Friendship)
  end

  def show
    @group_member = GroupMember.new
    @members = @group.members.to_a + [@group.admin]
    @members.sort! { |x, y| x.first_name <=> y.first_name }
    @group_statistics = group_statistics
    @message = Message.new
    @messages = @group.messages.reverse_order.page.reverse
    if @group.drink_in_progress # This logic could be better, consider attr_reader
      @drink = @group.drink_in_progress
      @drink_responses = @drink.drink_responses
    end
  end

  def new
    @group = Group.new
    authorize @group
  end

  def create
    @group = Group.new(group_params)
    @group.admin = current_user
    @group.members = user_id_params.map { |id| User.find(id) }

    authorize @group
    if @group.save!
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def group_params
    params.require(:group).permit(:name, :colour, :member_ids)
  end

  def user_id_params
    params[:group][:member_ids].delete('')
    params[:group][:member_ids]
  end

  def colours
    @colours = [
      'rgb(255, 255, 255)',
      'rgb(255, 45, 45)',
      'rgb(97, 216, 249)',
      'rgb(72, 48, 255)',
      'rgb(0, 165, 35)',
      'rgb(216, 76, 255)'
    ]
  end

  def find_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def group_statistics
    { 'Total drinks made' => 0, 'Avg. person per round' => 0, 'Hours since last brew' => 0 }
  end
end

app/views/groups/_add_new_member_modal.html.erb
<div class="modal fade" id="addMemberModal" tabindex="-1" role="dialog" aria-labelledby="addMemberModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addMemberModalLabel">Add a new member</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [group, group_member] do |f| %>

        <%= f.association :member, as: :check_boxes, collection: User.select{ |u| group.a_member?(u) == false && current_user.accepted_friends.include?(u) == true }, label_method: :full_name, value_method: :id %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add member", class: 'btn btn-primary' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_group_admin_options.html.erb
<div class="dropdown group-dropdown">
  <i class="fas fa-cog dropdown-toggle" data-toggle="dropdown"></i>
  <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
    <% if current_user.group_admin?(@group) %>
      <li>
        <a data-toggle="modal" data-target="#addMemberModal">
          <i class='fa fa-plus-circle'></i> Add member
        </a>
      </li>
      <li>
        <a id="removeAMemberBtn"><i class="fa fa-times"> </i> Remove member</a>
      </li>
    <% end %>
    <li>
      <%= link_to group_group_member_path(@group, current_user), method: :delete do %>
        <p><i class="fa fa-trash"></i> Leave group</p>
      <% end %>
    </li>
  </ul>
</div>

app/views/groups/_group_members.html.erb
<div class="group-members">
  <h4>Group Members</h4>
  <% members.each do |member| %>
    <div class="group-member">
      <% if current_user.group_admin?(group) %>
        <%= link_to group_group_member_path(group, member), method: :delete, data: { confirm: 'Are you sure?' }, class: "remove-members hidden" do %>
          <i class="fa fa-times"></i>
        <% end %>
      <% end %>
      <p><%= member.full_name %> </p>
      <% if member.group_admin?(group) %>
        <p class="admin-badge"><%= "Admin" %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="container padded">
  <div class="row">
    <% if @groups.empty? %>
      <div class="col-xs-12 text-center">
        <%= link_to "Create your first group!", new_group_path, class: "btn btn-primary" %>
      </div>
    <% else %>
      <div class="col-xs-12">
        <h2>Your groups</h2>
      </div>
      <% @groups.each do |group| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to group_path(group) do %>
            <div class="group-card" style="background-color: <%= group.colour %>; color: <%= 'black' if group.colour == 'rgb(255, 255, 255)'%>">
              <div class="group-card-content">
                <p><%= group.name %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to new_group_path do %>
          <div class="group-card new-group">
            <div class="group-card-content">
              <p><i class="fa fa-plus-circle"></i> Create a new group</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h2>Your friends</h2>

      <% @friends.each do |friend| %>
        <p><%= friend %></p>
      <% end %>
      <br>
      <%= link_to "Find friends", friendships_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="devise-form">
        <h2 class="text-center">Create a new group</h2>
        <br>
        <%= simple_form_for @group do |f| %>
          <%= f.error_notification %>
          <%= f.input :name, label: "Enter your group name:", placeholder: "Awesome group name", input_html: { maxlength: 26 } %>
          <%= f.input :colour, as: :hidden %>
          <div class="form-label">
            Pick a colour for your group:
          </div>

          <div class="colour-picker">
            <% @colours.each do |colour| %>
              <div class="colour-picker-btn" style="background-color: <%= colour %>;"></div>
            <% end %>
          </div>

          <%= f.association :members, as: :check_boxes, collection: current_user.accepted_friends, label: "Friends:", label_method: :full_name, value_method: :id %>

          <%= f.button :submit, class: "btn btn-primary wide-btn " %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", () => {

    const addColourSelect = (event) => {
      // Remove any current active classes
      document.querySelectorAll(".colour-picker-btn").forEach((btn) => {
        btn.classList.remove("active");
      });
      // Add active class to current colour selection
      event.currentTarget.classList.add("active");

      // Retrive the rgb colour and enter it in the form
      var colour = event.currentTarget.style.backgroundColor;
      document.querySelector("#group_colour").value = colour;
    };

    // Add event listner to all colour picker buttons
    document.querySelectorAll(".colour-picker-btn").forEach((btn) => {
      btn.addEventListener("click", addColourSelect);
    });
});
</script>

app/views/groups/show.html.erb
<div class="container">
  <div class="group-navigation">
    <%= link_to groups_path do %>
      <p style="padding-top: 10px;"><i class="fa fa-arrow-circle-left"></i> Back to your groups</p>
    <% end %>
    <%= render 'group_admin_options' %>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h2 class="text-center"><%= @group.name %></h2>
      <div class="group-stats">
        <% @group_statistics.each do |title, value| %>
          <div class="group-stat">
            <div class="stat-figure"><%= value %></div>
            <div class="stat-title"><%= title %></div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="drink-container">
        <% if @drink %>
          <div id="drink-view">
            <%= render 'drinks/drink', drink: @drink, user: current_user %>
          </div>
        <% else %>
          <%= simple_form_for [@group, Drink.new], remote: true do |f| %>
            <%= f.error_notification %>
            <%= f.input :limit, input_html: { value: 5 } %>
            <%= f.submit 'Make tea', class: 'btn btn-primary' %>
          <% end %>
          <div id="drink-view">
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <h4 id="messages-panel-header" class="text-center">Messages</h4>
        <div id="messages-panel">
          <form action="/groups/<%= @group.id %>/messages" method="get" data-remote="true" id="load-messages-form">
            <input id="pagination_counter" type="text" name="page" value="2" class="hidden">
          </form>
          <div id="message-load-icon"><i class="fas fa-spin fa-sync-alt"></i></div>
          <div id="messages">
            <% @messages.each do |message| %>
              <%= render 'messages/message', message: message, user_is_author: message.user == current_user %>
            <% end %>
          </div>
        </div>
      <br>
      <div id="create-message">
        <%= simple_form_for [@group, Message.new], remote: true do |f| %>
          <%= f.input :content, as: :string, label: false %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= render 'groups/group_members', group: @group, members: @members %>
    </div>
  </div>
</div>

<%= render 'add_new_member_modal', group: @group, group_member: @group_member %>

<% content_for :after_js do %>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      // Load new messages logic
      scrollLastMessageIntoView();

      App['group_<%= @group.id %>'] = App.cable.subscriptions.create(
        { channel: 'GroupsChannel', group_id: <%= @group.id %> },
        { received: (data) => {
            if (data.current_user_id !== <%= current_user.id %>) {
              if (data.type === 'message') {
                const messagesContainer = document.querySelector('#messages');
                messagesContainer.insertAdjacentHTML('beforeend', data.partial);
                scrollLastMessageIntoView();
              } else if (data.type === 'create_drink') {
                const newDrinkForm = document.getElementById('new_drink');
                newDrinkForm.style.display = 'none';

                const drinksContainer = document.getElementById("drink-view");
                drinksContainer.insertAdjacentHTML('beforeend', data.partial);
              } else {
                console.log('update');
                const drinksContainer = document.getElementById("drink-view");
                drinksContainer.innerHTML = data.partial;

                const requestDrinkBtn = document.getElementById('request-drink-btn');
                requestDrinkBtn.style.display = 'none';
              }
            }
          }
        }
      )

      // Remove member logic - need to alter!!!!!!
      let admin = false;

      if (admin) {
        const revealBtns = (event) => {
          document.querySelectorAll('.remove-members').forEach((member) => {
            member.classList.toggle("hidden");
          });
        };

        const btn = document.querySelector("#removeAMemberBtn");

        btn.addEventListener("click", revealBtns);

      }


      // Load new messages
      let messagesPanel = document.getElementById('messages-panel');
      let loadIcon = document.getElementById('message-load-icon');

      messagesPanel.addEventListener('scroll', () => {
        if (inView(messagesPanel, loadIcon) === true) {
          let form = document.getElementById('load-messages-form');
          Rails.fire(form, 'submit');
        }
      })
    });
  </script>
<% end %>
<!-- <script type="text/javascript">
  document.addEventListener("DOMContentLoaded", () => {


  });

  document.addEventListener("DOMContentLoaded", () => {
    var messagesPanel = document.getElementById('messages-panel');
    var messageTitle = document.getElementById('messages-panel-header');
    var loadIcon = document.getElementById('message-load-icon');

    messagesPanel.addEventListener('scroll', () => {
      if (loadIconInView(messageTitle, loadIcon)) {
        // Load old messages
        var form = document.getElementById('load-old-messages-form');
        Rails.fire(form, 'submit');
      }
    })

    var loadIconInView = (messageTitle, loadIcon) => {
      var diff = loadIcon.getBoundingClientRect().y - messageTitle.getBoundingClientRect().y
      if (diff > 62 ) {
        return true
      } else {
        return false
      }
    }

    // messagesPanel.addEventListener('scroll', getOldMessages());
  });
</script> -->