config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :groups do
    resources :group_members, only: [:new, :create, :destroy]

    resources :messages, only: [:create, :index]

    resources :drinks, only: [:create, :update] do
      resources :drink_responses, only: [:create]
    end
  end

  resources :friendships, only: [:index, :update]

  resources :users, only: [] do
    resources :friendships, only: [:create]
  end

  get 'profile/:id', to: 'pages#user_profile', as: :user_profile
end

app/views/shared/_flashes.html.erb
<% if notice%>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <% if user_signed_in? %>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Friend request notifications -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="fa fa-users navbar-icon dropdown-toggle" data-toggle="dropdown"></i>
          <% unless current_user.friend_requests.empty? %>
            <p class="notification-badge" id="friend-request-notification"><%= current_user.friend_requests.size %></p>
          <% end %>
            <ul id="friend-request-dropdown" class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to "Find Friends", friendships_path, class: "text-center" %></li>
              <% if current_user.friend_requests.empty? %>
                <li><p>No new requests.</p></li>
              <% else %>
                <% current_user.friend_requests.each do |fr| %>
                  <li class="flex friend-request" data-friend-request-id="<%= fr.id %>" >
                    <%= link_to fr.user.full_name, user_profile_path(fr.user), class: "friend-request-user" %>
                    <div class="flex" id="friend-request-response-<%= fr.id %>">
                      <%= link_to "Accept", friendship_path(fr, status: "accepted"), method: :patch, remote: true, class: "friend-request-link" %>
                      <%= link_to "Decline", friendship_path(fr, status: "declined"), method: :patch, remote: true, class: "friend-request-link" %>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
      </div>
      <!-- My groups -->
      <div class="navbar-wagon-item">
        <%= link_to "My groups", groups_path, id: "sign-up-btn", title: "My groups", class: "navbar-btn" %>
      </div>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= user_avatar_photo(current_user, {class: "avatar dropdown-toggle navbar-icon", id: "navbar-wagon-menu", data_toggle: "dropdown"}) %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item navbar-wagon-link hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-wagon-right">
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-btn", id: "sign-in-btn" %>
      <!-- Sign Up link (when logged out) -->
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-btn", id: "sign-up-btn" %>
    </div>
  <% end %>
</div>