config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  # end

  root to: 'pages#home'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :groups do
    resources :group_members, only: [:new, :create, :destroy]

    resources :messages, only: [:create, :index]

    resources :drinks, only: [:create, :update] do
      resources :drink_responses, only: [:create]
    end
  end

  resources :friendships, only: [:index, :update]

  resources :users, only: [] do
    resources :friendships, only: [:create]
  end

  get 'profile/:id', to: 'pages#user_profile', as: :user_profile
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  enum status: %i[pending accepted declined blocked]

  validates :status, presence: true

  before_create :user_cannot_be_own_friend

  def user_cannot_be_own_friend
    raise 'You cannot send yourself a friend request' if user_id == friend_id

    true
  end

  # validates :friend, uniqueness: { scope: :user, message: 'You cannot add yourself as a friend' }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :find_friendship, only: [:update]

  def index
    @users = policy_scope(User).reject { |user| user == current_user }
  end

  def create
    @friendship = Friendship.new(user: current_user, friend: find_user)
    authorize @friendship
    @friendship.save
    redirect_to(request.env['HTTP_REFERER'])
  end

  def update
    @friendship.update(status: params[:status])

    flash[:alert] = "An error has occured." unless @friendship.save

    respond_to do |format|
      format.html { redirect_to request.env['HTTP_REFERER'] }
      format.js
    end
  end

  private

  def find_user
    User.find(params[:user_id])
  end

  def find_friendship
    @friendship = Friendship.find(params[:id])
    authorize @friendship
  end
end

app/views/friendships/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @users.each do |user| %>
        <ul class="list-inline">
          <li><p><strong><%= user.full_name %></strong></li>
          <% if user.accepted_friends.include?(current_user) %>
            <li>- Friend</p></li>
          <% elsif user.pending_friends.include?(current_user) %>
            <li><p>- Request pending</p></li>
          <% else %>
            <li><%= link_to "Add friend", user_friendships_path(user), method: :post %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/friendships/update.js.erb
var friendRequest = document.querySelector("#friend-request-response-<%= @friendship.id %>");

const status = '<%= @friendship.status.capitalize %>!';

const newText = "<a href='javascript:void(0)'>" + status + "</a>";

friendRequest.innerHTML = newText;
// document.getElementById("friend-request-dropdown").innerHTML = "<li><a>No new requests.</a></li>";

const notification = document.querySelector("#friend-request-notification");
var counter = parseInt(notification.innerText);

if (counter - 1 == 0) {
  notification.remove();
} else {
  notification.innerText = counter - 1;
}